config/routes.rb
Rails.application.routes.draw do

  root to: "static_pages#homepage"
  get "/about", to: "static_pages#about"
  get "/portfolio", to: "static_pages#portfolio"
  get "/blog", to: "admins#index"
  get	"/blog/:id", to: "blogs#show"
  get	"/blog/:id/edit", to: "blogs#edit"
  patch "/blog/:id/", to: "blogs#update", as: "patch"


  resources :admins
  resources :blogs

  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"
  post "/sessions", to: "sessions#create"

end

app/models/admin.rb
class Admin < ActiveRecord::Base

  #bcrypt secure password
  has_secure_password

  #for paperclip usage
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  #admin has many blogs
  has_many :blogs

  #sign in confirming
  def self.confirm(params)
    @admin = Admin.find_by({email: params[:email]})
    @admin.try(:authenticate, params[:password])
  end
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :admins
  
  #for paperclip
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
    @admin = Admin.find_by_id(params[:id])
  end

  def show
    @admin = Admin.find_by_id(params[:id])
  end

  def create
    admin_params = params.require(:admin).permit(:first_name, :last_name, :email, :github, :twitter, :city, :state, :password, :avatar)
    @admin = Admin.create(admin_params)
    redirect_to root_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @blogs = Blog.all
  end

  def new
    if current_admin == nil
      redirect_to root_path
    else
    @blog = Blog.new
    render :new
    end
  end

  def show
    blog_id = params[:id]
    @blogs = Blog.find_by_id(blog_id)
    render :show
  end

  def create
    blog_params = params.require(:blog).permit(:title, :body, :avatar).merge(admin_id: current_admin.id)
    @blog = Blog.create(blog_params)
    redirect_to root_path
  end

  def edit
    blog_id = params[:id]
    @blog = Blog.find_by_id(blog_id)
    render :edit
  end

  def update
    blog_id = params[:id]
    blog = Blog.find_by_id(blog_id)
    blog_params = params.require(:blog).permit(:title, :body, :avatar)
    blog.update_attributes(blog_params)
    redirect_to root_path
  end

  def destroy

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @admin = Admin.new
    render :new
  end

  def create
    admin_params = params.require(:admin).permit(:email, :password)
    @admin = Admin.confirm(admin_params)
    if @admin
      login(@admin)
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    logout
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/helpers/admins_helper.rb
module AdminsHelper
    def blog_posts
      Blog.all.order('updated_at DESC')
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(admin)
    session[:admin_id] = admin.id
    @current_admin = admin
  end

  def current_admin
    @current_admin ||= Admin.find_by_id(session[:admin_id])
  end

  def logged_in?
    if current_admin == nil
      redirect_to new_session_path
    end
  end

  def logout
    @current_admin = session[:admin_id] = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def last_five_posts
    Blog.limit(5).order('id desc')
  end
  def blog_entry(blog)
    Blog.find_by_id(blog.id)
  end
end

app/views/admins/index.html.erb
<div class="container blogs">
  <div class="row">
    <% blog_posts.each do |blog| %>
    <div class="col s12 post">
      <%= link_to blog_path(blog_entry(blog)).gsub!(/[."]/,'/') do %>
      <h4 cl> <%= blog.title %> <small></small></h4>
      <% end %>
      <p class="black-text">
        <%= blog.body %>
        <br>
        <small class="blue"> <%= blog.created_at.strftime("%m-%d-%Y") %> </small>
      </p>
    </div>
    <% end %>
  </div>
</div>

app/views/blogs/edit.html.erb
<div class="container blogs">
  <div class="row card white hero">
    <h4 class=" center-align card blue white-text z-depth-2 ">Edit Blog Post</h4>
  </div>
  <div class="row white">
      <div class="col s12">
        <%= form_for @blog, url: patch_path, method: "patch"  do |f| %>
        <div class="input-field col s6">
          <%= f.label(:title, "Title") %>
          <br>
          <%= f.text_field :title %>
        </div>
        <div class="input-field col s6">
          <%= f.label(:body, "Body") %>
          <br>
          <%= f.text_area :body %>
        </div>
      </div>
      <%= f.submit "Save", class: "btn blue" %>
      <% end %>
  </div>
</div>

app/views/blogs/new.html.erb
<div class="container blogs">
  <div class="row card white hero">
    <h4 class=" center-align card blue white-text z-depth-2 ">New Blog Post</h4>
  </div>
  <div class="row white">
    <div class="col s12">
      <%= form_for @blog do |f| %>
      <div>
        <%= f.text_field :title, placeholder: "Title" %>
      </div>
      <div>
        <%= f.text_area :body, placeholder: "Post" %>
      </div>
      <%= f.submit "New Post", class: "btn blue" %>
      <% end %>
  </div>
</div>

app/views/blogs/show.html.erb
<div class="container blogs">
  <div class="row">
    <h4 class=" center-align blue-text"><%= @blogs.title %></h4>
  </div>
  <div class="row">
    <div class="col s12 post">
      <div>
      <p class="black-text">
        <%= @blogs.body %>
      </p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Breon Knight</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600italic|Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar-fixed">
    <nav class="blue">
      <div class="nav-wrapper">
        <a href="/" class="brand-logo">Breon Knight</a>
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
          <% if current_admin %>
            <li><%= link_to 'Blog', blog_path, class: "top-link" %></li>
            <li><%= link_to 'New Blog Post', new_blog_path, class: "top-link" %></li>
            <li><%= link_to 'About', about_path, class: "top-link" %></li>
            <li><%= link_to 'Portfolio', portfolio_path, class: "top-link" %></li>
            <li><%= link_to "Log Out", logout_path, class: "top-link" %></li>
          <% else %>
            <li><%= link_to 'Blog', blog_path, class: "top-link" %></li>
            <li><%= link_to 'About', about_path, class: "top-link" %></li>
            <li><%= link_to 'Portfolio', portfolio_path, class: "top-link" %></li>
            <li><a href="/BreonKnightResume.pdf" class="top-link">Resume</a></li>
</li>
          <% end %>
        </ul>
        <ul class="side-nav" id="mobile-demo">
          <% if current_admin %>
          <li><%= link_to 'Blog', blog_path %></li>
          <li><%= link_to 'New Blog Post', new_blog_path %></li>
          <li><%= link_to 'About', about_path %></li>
          <li><%= link_to 'Portfolio', portfolio_path %></li>
          <li><%= link_to "Log Out", logout_path %></li>
        <% else %>
          <li><%= link_to 'Blog', blog_path %></li>
          <li><%= link_to 'About', about_path %></li>
          <li><%= link_to 'Portfolio', portfolio_path %></li>
          <li><a href="BreonKnightResume.pdf">Resume</a></li>
</li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>

  <% flash.each do |name, msg| %>
    <p>
      <small> <%= name.capitalize %>: <%= msg %> </small>
    </p>
  <% end %>
<main>

  <%= yield %>
</main>
  <footer class="page-footer blue">
    <div class="container">
      <div class="row">
        <div class="col 4">
          <h5 class="white-text"> Connect with Me</h5>
          <ul class="social">
            <li><a class="grey-text text-lighten-3" href="https://github.com/BreonKnight"><i class="fa fa-github fa-2x"></i> Github</a></li>
            <li><a class="grey-text text-lighten-3" href="https://www.linkedin.com/in/brekni"><i class="fa fa-linkedin fa-2x"></i> LinkedIn</a></li>
            <li><a class="grey-text text-lighten-3" href="mailto:breonknight7@gmail.com?Subject=Hi,%20Breon" target="_top"><i class="fa fa-envelope fa-2x"></i> Email Me</a></li>
            <li><a class="grey-text text-lighten-3" href="https://soundcloud.com/illusiveness"><i class="fa fa-soundcloud fa-2x"></i> Soundcloud</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">

        © 2016 Breon Knight

      </div>
    </div>
  </footer>
</body>
</html>

app/views/static_pages/about.html.erb
<div class="container">
  <div class="row">
    <div class="col s12">
      <img class=" card responsive-img" src="/images/london.jpg">
    </div>
    <div class="col s12">
      <p class="card blue white-text">
        My name is Breon Knight. I really enjoy programming, reading manga, videogames, basketball, and eating seafood. I'm a big fan of
         the Final Fantasy and Resident Evil videogame series. Hunter x Hunter is currently my favorite manga series. I'm a huge nerd when it comes to
        synthesizers. My goal before 2017 is to purchase a diy synth kit.
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col s12">
      <img class=" card responsive-img" src="/images/illusive.jpg">
    </div>
    <div class="col s12">
      <p class="card blue white-text">
        For music I go under the name illusive. I got to travel alot of awesome places because of it. I'm releasing my first album soon. This is a track from the album.
      </p>
      <iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/157295979&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>
    </div>
  </div>
  <div class="row">
    <div class="col s12">
      <img class=" card responsive-img" src="/images/apollo.jpg">
    </div>
    <div class="col s12">
      <p class="card blue white-text">
        I'm a owner of a Chow Chow named Apollo. He's my heart :)
      </p>
    </div>
  </div>
</div>

app/views/static_pages/homepage.html.erb
<div id="index-banner" class="parallax-container grad-text">
  <div class="section no-pad-bot">
    <div class="container">
      <br><br>
      <h1 class="header center">Breon Knight</h1>
      <div class="row center">
        <h5 class="header col s12 light"> Welcome to my site</h5>
      </div>
      <div class="row center">
        <a href="http://www.breonknight.com/portfolio" id="download-button" class="btn-large waves-effect blue">Projects</a>
      </div>
      <br><br>

    </div>
  </div>
  <div class="parallax grad-text"><img class="grad-text" src="/images/arizona.jpg" alt="Unsplashed background img 1"></div>
</div>


<div class="container">
  <div class="section">
    <!--   Icon Section   -->
    <div class="row">
      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center blue-text"><i class="material-icons">flash_on</i></h2>
          <h5 class="center">Fast Learner</h5>

          <p class="light">
                  My passions lie in creating functional applications. My goals are to create applications that people
                  want to use in the simplest manner.</p>
        </div>
      </div>
      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center blue-text"><i class="material-icons">code</i></h2>
          <h5 class="center">Technologies</h5>

          <p class="light">Java, Swift, Javascript, Ruby, Ruby on Rails, CSS3, HTML5, Node.js, Express.js, Angular,
            MongoDB, PostgresSQL, and SQL </p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center blue-text"><i class="material-icons">location_on</i></h2>
          <h5 class="center">Location</h5>

          <p class="light">I'm from Charm City: Baltimore, Maryland. I'm currently residing in Berkeley, California working freelance.</p>
        </div>
      </div>
    </div>

  </div>
</div>

<div class="parallax-container valign-wrapper">
  <div class="section no-pad-bot">
    <div class="container">
      <div class="row">
        <h2 class="header col s12 light">Passionate about UI sensibilities</h2>
      </div>
    </div>
  </div>
  <div class="parallax grad-text"><img src="/images/nyc.jpg" alt="Unsplashed background img 2"></div>
</div>

<div class="container">
  <div class="section">
    <h3 class="header col s12 light">Recent Posts</h3>
    <div class="row">
          <% last_five_posts.each do |post| %>
          <%= link_to blog_path(blog_entry(post)).gsub!(/[."]/,'/') do %>
          <div class="col s6">
            <h5 class="card blue white-text"><%= post.title %> <br><small class="white-text"><%= truncate(post.body, :length => 50) -%></small></h5>
            <% end %>
          </div>
          <% end %>
      </div>
    </div>
</div>

<div class="parallax-container valign-wrapper">
  <div class="section no-pad-bot">
    <div class="container">

    </div>
  </div>
  <div class="parallax grad-text"><img src="/images/japan.jpg" alt="Unsplashed background img 3"></div>
</div>

app/views/static_pages/portfolio.html.erb
<div class="container">
  <h1>Under Construction</h1>
</div>